config/routes.rb
Manage::Application.routes.draw do
  resources :listings

  resources :comments

  devise_for :users
  
  get "rolluplisting/index"
  
  root :to => 'home#index'
  
   resources :users do
    post 'edit_individual', :on => :collection
    put 'update_individual', :on => :collection
  end

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user

    if user.role_name == "Client"
      can :read, :all
    elsif user.role_name ==  "Manager"
      can :manage, :all
    elsif user.role_name ==  "Employee"
      can :update, :all
    elsif user.role_name == "Admin"
      can :manage, :all
    end
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
belongs_to :user
belongs_to :listing
attr_accessible :content, :user_id, :listing_id
end

app/models/listing.rb
class Listing < ActiveRecord::Base
attr_accessible :image, :name, :content, :desription, :address, :city, :state, :user_id, :remote_image_url  
mount_uploader :image, ImageUploader

belongs_to :user
has_many :comments

end

app/models/user.rb
class User < ActiveRecord::Base
ROLE_TYPES = ["Client", "Manager", "Employee", "Admin"]
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :f_name, :l_name, :phone, :role_name

has_many :listings
has_many :comments

def client
  clients = User.count(:conditions => [:role_name == "Client"])
  end
def manager
  managers = User.count(:conditions => [:role_name == "Manager"])
  end
def employee 
  employees = User.count(:conditions => [:role_name == "Employee"])
  end
def hefe
  hefes = User.count(:conditions => [:role_name == "Admin"])
  end
def fullname
"#{f_name.humanize}" " " "#{l_name.humanize}"
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
     redirect_to root_url, :alert => exception.message
   end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  respond_to :html, :js

  def index
    @comments = Comment.all
  end

  def create
    @comment = Comment.new(params[:comment])

    @comment.save

    respond_with @comment, :location => comments_url
  end

  def destroy
    @comment = Comment.find(params[:id])

    @comment.destroy

    respond_with @comment, :location => comments_url
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
 def index

  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
#load_and_authorize_resource
  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @listings }
    end
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @listing = Listing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @listing }
    end
  end

  # GET /listings/new
  # GET /listings/new.json
  def new
    @listing = Listing.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @listing }
    end
  end

  # GET /listings/1/edit
  def edit
    @listing = Listing.find(params[:id])
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(params[:listing])

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render json: @listing, status: :created, location: @listing }
      else
        format.html { render action: "new" }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /listings/1
  # PUT /listings/1.json
  def update
    @listing = Listing.find(params[:id])

    respond_to do |format|
      if @listing.update_attributes(params[:listing])
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy

    respond_to do |format|
      format.html { redirect_to listings_url }
      format.json { head :ok }
    end
  end
end

app/controllers/rolluplisting_controller.rb
class RolluplistingController < ApplicationController 
 def index
 @listings = Listing.find(:all)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
	@users = User.all(:order => "last_name ASC")	
	@usersummary = User.all(:limit =>'1')
  end
  def edit_individual
    @users = User.order("last_name ASC")
  end

  def update_individual
   User.update(params[:users].keys, params[:users].values)  
   redirect_to users_url, :notice => 'Users Succesfully Updated'   

  end

  def destroy
    @users = User.find(params[:id])
    @users.destroy

    respond_to do |format|
      format.html { redirect_to(users_url, :notice => 'Users Removed') }
      format.xml  { head :ok }
      format.js
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/comments/_comment.html.erb
<div id=<%= dom_id(comment) %> class="comment">
  <strong><%= comment.user_id %></strong>
  <em>on <%= comment.created_at.strftime('%b %d, %Y at %I:%M %p') %></em>
  <%= link_to "Remove", comment, :method => :delete, :remote => true %>
  <%= simple_format comment.content %>
</div>

app/views/comments/_form.html.erb
<%= form_for(@comment) do |f| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :listing_id %><br />
    <%= f.number_field :listing_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<title> Comments for Ajax in Rails 3.1 </title>

<h3>Add your comment:</h3>

<%= form_for Comment.new, :remote => true do |f| %>
 <p>
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </p> 
  <p>
    <%= f.label :content, "Comment" %><br />
    <%= f.text_area :content, :rows => '12', :cols => 35 %>
  </p>
  <p><%= f.submit %></p>
<% end %>
<div id="comments">
  <%= render @comments %>
</div>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @comment.content %>
</p>

<p>
  <b>User:</b>
  <%= @comment.user_id %>
</p>

<p>
  <b>Listing:</b>
  <%= @comment.listing_id %>
</p>


<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/home/index.html.erb
<h2>HomePage</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Manage</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
 <li><a><%= link_to "Home", root_path %></a></li>
 <% if can? :read, :all %>
 <li><a><%= link_to "View Listings", rolluplisting_index_path %></a></li>
 <li><a><%= link_to "Listing Create/Update", listings_path %></a></li>
 <% else %>
 <li><a><%= link_to "Listing Create/Update", listings_path %></a></li>
 <% end %>
<%= yield %>

</body>
</html>

app/views/listings/_form.html.erb
<%= form_for @listing, :html => {:multipart => true} do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :desription %><br />
    <%= f.text_area :desription %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
  <%= f.file_field :image %>
  </div>
  <div class="field">
  <%= f.label :remote_image_url, "or image URL" %>  
    <%= f.text_field :remote_image_url %> 
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<h1>Listing listings</h1>
<table>
  <tr>
    <th>Name</th>
    <th>Content</th>
    <th>Desription</th>
    <th>Address</th>
    <th>City</th>
    <th>State</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @listings.each do |listing| %>
  <tr>
    <td><%= listing.name %></td>
    <td><%= listing.content %></td>
    <td><%= listing.desription %></td>
    <td><%= listing.address %></td>
    <td><%= listing.city %></td>
    <td><%= listing.state %></td>
    <td><%= listing.user_id %></td>
    <td><%= listing.image %></td>
    <td><%= link_to 'Show', listing %></td>
    <td><%= link_to 'Edit', edit_listing_path(listing) %></td>
    <td><%= link_to 'Destroy', listing, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Listing', new_listing_path %>

app/views/listings/new.html.erb
<h1>New listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @listing.name %>
</p>

<p>
  <b>Content:</b>
  <%= @listing.content %>
</p>

<p>
  <b>Desription:</b>
  <%= @listing.desription %>
</p>

<p>
  <b>Address:</b>
  <%= @listing.address %>
</p>

<p>
  <b>City:</b>
  <%= @listing.city %>
</p>

<p>
  <b>State:</b>
  <%= @listing.state %>
</p>

<%= image_tag @listing.image_url(:thumb).to_s %>    
    </div>  


<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>

app/views/rolluplisting/index.html.erb
<h2>All Listings</h2>
<% @listings.each do |listing| %>
<p><%= listing.name %></p>
<p><%= listing.content %></p>
<p><%= listing.desription %></p>
<p><%= listing.state %></p>
<% end %>

app/views/users/_fields.html.erb
<br />
<%= f.select :role_name, User::ROLE_TYPES, :prompt => "Select a Role" %> 
<br />

    

app/views/users/_form.html.erb
<% form_for @user do |f| %>
<%= render :partial => 'fields', :f => f %>
<p><%= form.submit "Submit" %></p>
<% end %>

app/views/users/edit_individual.html.erb
<%= form_tag update_individual_users_path, :method => :put do %>  

   <title>Edit User Status & Role</title>
   <h3>Edit User Status & Role</h3>
   <div id="formsEditIndividual">
          <% @users.each do |user| %>  
        <b><%= user.fullname%>
<%= fields_for "users[]", user do |f| %> 
		<%= render 'fields', :f => f %>
		<br />
    <% end %>  
   <% end %>
   </div>
    <div id="submitEUsers">
   <p><%= submit_tag "Submit" %> or <%= link_to 'Cancel', users_path %></p>  
<% end %>
</div>

app/views/users/index.html.erb
<% if can? :manage, :all %>
 <title>Users Index Page</title>
<h3>All Users</h3>
<div id="formsuserALL">
<%= form_tag edit_individual_users_path do %>
<div id="submituserALL">
<%= submit_tag "Edit All Users" %>
<p></p>
</div>
</div>
<% @usersummary.each do |usersummary| %>
<h2></h2>
<div id='usercontainermain'>
<div id='usersummarymain'>
User Summary
<p>Clients <%= usersummary.client %><br/>
Managers <%= usersummary.manager %><br/>
Employees <%= usersummary.employee %><br/>
Admin <%= usersummary.hefe %><br/>
</div>
</div>
<% end %>
<table border= '1'>
  <tr>
    <th>Name</th>
    <th>Role</th>
    <th>Email</th>
    <th>Phone Number</th>
    <th>Sign-in Counter</th>
    <th>Last Sign-in</th>
    <th></th>  
  </tr>

<% @users.each do |user| %>
  <tr>
    <td align='center'><%= user.fullname %></td>
    <td align= 'center'><%= user.role_name %></td>
    <td align='center'><%= user.email %></td>
    <td align='center'><%= user.phone %></td>
    <td align='center'><%= user.sign_in_count %></td>
    <td align='center'><%= user.last_sign_in_at %></td>
    <td><%= link_to 'Remove', user, :method => :delete %></td>   
 </tr>
  <% end %>
	</table>	
<br />
</div>
<% end %>

<% else %>
<title>Unauthorized Access</title>
<h3 align='center'>Unauthorized Access</h3>
<div id="adminError"><p>You Are Not Authorized To View This Page!</p></div>
<div id="submit">
<%= link_to 'Get Me Out', root_path %>
</div>
<% end %>